nadeemlab/SPT

- spatialprofilingtoolbox/workflows/density/computational_design.py
- spatialprofilingtoolbox/workflows/density/core.py
- tests/tests_integration.sh
Addressed #24 . Distance to nearest cell in each compartment has been implemented.
> additional metrics in density workflow

- spatialprofilingtoolbox/workflow/common/extract_compartments.py
- spatialprofilingtoolbox/workflow/dataset_designs/multiplexed_imaging/file_identifier_schema.py
Addresses #112 by removing warnings about compartment data.
This PR should be mergeable at any time.
> Deprecating irrelevant warnings, compartments

- build/apiserver/Makefile
- build/cggnn/Makefile
- build/countsserver/Makefile
- build/db/Makefile
- build/workflow/Makefile
- pyproject.toml
- spatialprofilingtoolbox/workflow/tabular_import/parsing/cell_manifest_set.py
- spatialprofilingtoolbox/workflow/tabular_import/parsing/channels.py
- test/apiserver/module_tests/expected_study_summary.json
> Fix hardcoded values for measurement assay

- spatialprofilingtoolbox/apiserver/__init__.py
- spatialprofilingtoolbox/apiserver/app/main.py
> Normalize cohort identifier values for display

- spatialprofilingtoolbox/apiserver/__init__.py
- spatialprofilingtoolbox/apiserver/app/main.py
- test/apiserver/unit_tests/expected_study_names.json
- test/apiserver/unit_tests/test_study_names.sh
> Publication info in dataset handles

- Makefile
- build/build_scripts/check_for_credentials.py
- spatialprofilingtoolbox/apiserver/app/db_accessor.py
- spatialprofilingtoolbox/apiserver/app/main.py
- spatialprofilingtoolbox/ondemand/compressed_matrix_writer.py
- spatialprofilingtoolbox/ondemand/counts_request_handler.py
- spatialprofilingtoolbox/ondemand/proximity_provider.py
- spatialprofilingtoolbox/ondemand/scripts/cache_expressions_data_array.py
- spatialprofilingtoolbox/ondemand/scripts/start.py
- test/apiserver/unit_tests/test_api_internal_basic_database_accessor.py
- test/apiserver/unit_tests/test_expressions_in_db.py
As part of the work in #162 the DBAccessor usage is slightly simplified. This is ready to merge in (before #162 is complete).
> Some db accessor cleanup

- spatialprofilingtoolbox/ondemand/__init__.py
- spatialprofilingtoolbox/ondemand/proximity_provider.py
- test/apiserver/module_tests/expected_proximity4.json
> Fix prox metric nulls bug

- spatialprofilingtoolbox/ondemand/fast_cache_assessor.py
- spatialprofilingtoolbox/ondemand/proximity_provider.py
> Reduce verbosity of some log statements

- pyproject.toml.unversioned
- spatialprofilingtoolbox/db/ondemand_dropper.py
- spatialprofilingtoolbox/db/scripts/drop_ondemand_computations.py
> Add db managements script to drop pending computatations

- analysis_replication/README.md
- analysis_replication/accessors.py
- analysis_replication/breast_imc.py
- analysis_replication/luad_imc.py
- analysis_replication/melanoma_ici.py
- analysis_replication/melanoma_il2.py
> Add replication of analysis scripts

- spatialprofilingtoolbox/ondemand/fast_cache_assessor.py
- spatialprofilingtoolbox/ondemand/scripts/start.py
> Add service-specific initialization logic. Waiting etc.

- spatialprofilingtoolbox/ondemand/providers/pending_provider.py
- spatialprofilingtoolbox/ondemand/providers/provider.py
- spatialprofilingtoolbox/ondemand/request_handler.py
- spatialprofilingtoolbox/workflow/common/export_features.py
Bug fix that addresses #223 .
In prototype instance testing, the pending behavior is restored.
> Make substudy consistent for ondemand computed features.

- spatialprofilingtoolbox/db/credentials.py
- spatialprofilingtoolbox/db/modify_constraints.py
- spatialprofilingtoolbox/db/schema_infuser.py
- spatialprofilingtoolbox/db/scripts/modify_constraints.py
- spatialprofilingtoolbox/db/scripts/status.py
- spatialprofilingtoolbox/workflow/tabular_import/parsing/skimmer.py
> Bug fix to some db management

- build/ondemand/Dockerfile
- spatialprofilingtoolbox/db/expressions_table_indexer.py
- spatialprofilingtoolbox/db/scripts/index_expressions_table.py
- spatialprofilingtoolbox/ondemand/providers/pending_provider.py
- spatialprofilingtoolbox/ondemand/providers/provider.py
- spatialprofilingtoolbox/ondemand/providers/proximity_provider.py
- spatialprofilingtoolbox/ondemand/providers/squidpy_provider.py
- spatialprofilingtoolbox/ondemand/scripts/start.py
- test/ondemand/unit_tests/test_timeout.sh
- test/ondemand/unit_tests/timeout.py
> Implement timeout for ondemand computations

- build/ondemand/Dockerfile
- spatialprofilingtoolbox/cggnn/scripts/run.py
- spatialprofilingtoolbox/workflow/assets/cggnn.nf
> Deal with NF string processing for cggnn

- build/build_scripts/development.Dockerfile
- pyproject.toml.unversioned
- spatialprofilingtoolbox/apiserver/app/main.py
> Remove unused cg-gnn requirement from pyproject

- analysis_replication/accessors.py
- analysis_replication/melanoma_il2.py
> il2 importance analysis

- analysis_replication/accessors.py
Closes #293 by patching DataAccessor.
> Quick patch to counts_by_signature to handle if one of positive or negative is empty

- build/build_scripts/import_test_dataset1.sh
- pyproject.toml.unversioned
- spatialprofilingtoolbox/apiserver/app/main.py
- spatialprofilingtoolbox/db/accessors/study.py
- spatialprofilingtoolbox/db/database_connection.py
- spatialprofilingtoolbox/db/exchange_data_formats/metrics.py
- spatialprofilingtoolbox/db/exchange_data_formats/study.py
- spatialprofilingtoolbox/db/querying.py
- spatialprofilingtoolbox/db/scripts/upload_sync_findings.py
- spatialprofilingtoolbox/graphs/plugin_constants.py
- test/apiserver/unit_tests/test_available_gnn.sh
- test/apiserver/unit_tests/test_findings.sh
- test/test_data/findings.json
> More study detail from API service

- spatialprofilingtoolbox/apiserver/app/main.py
This is a quick, temporary fix for the issue described in #314 .
> Implement cell limit for cells data query

- Makefile
- spatialprofilingtoolbox/db/data_model/performance_tweaks.sql
- spatialprofilingtoolbox/ondemand/scheduler.py
> Bug fix key conflict

- spatialprofilingtoolbox/apiserver/app/main.py
- spatialprofilingtoolbox/graphs/importance_fractions.py
- test/apiserver/module_tests/test_retrieval_of_gnn_plot.sh
> Cache GNN plots

- Makefile
- build/apiserver/Dockerfile
- build/apiserver/compose.yaml
- build/ondemand/Dockerfile
- build/ondemand/compose.yaml
- requirements.apiserver.txt
- requirements.ondemand.txt
- requirements.txt
Addresses #394 . After new code changes the additional build time during testing is now about 10 seconds. Also requirements pins are recomputed less frequently now
> Docker speedup
